/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package itson.edu.mx.autobus.ui;

import itson.edu.mx.autobus.business.Operation;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author yato_
 */
public class Usuario extends javax.swing.JFrame {

    private JTextField txtNombre, txtDestino, txtPrecio;
    private JComboBox<String> cmbCombo;
    private Operation operacion;
    
    public Usuario(Operation operacion) {
        this.operacion = operacion;
        setTitle("Venta de Boleto");
        setLayout(new FlowLayout());
        
        JLabel nombreLabel = new JLabel("Nombre:");
        txtNombre = new JTextField(20);
        
        JLabel destinoLabel  = new JLabel("Destino:");
        txtDestino = new JTextField(20);
        
        JLabel precioLabel  = new JLabel("Precio:");
        txtPrecio = new JTextField(10);
        
        // Asientos disponibles
        JLabel asientoLabel   = new JLabel("Selecciona Asiento:");
        cmbCombo = new JComboBox<>();
        actualizarAsientosDisponibles();

        JButton venderBoletoButton = new JButton("Vender Boleto");
        venderBoletoButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                venderBoleto();
            }
        });
        add(nombreLabel);
        add(txtNombre);
        add(destinoLabel);
        add(txtDestino);
        add(precioLabel);
        add(txtPrecio);
        add(asientoLabel);
        add(cmbCombo);
        add(venderBoletoButton);

        setSize(300, 250);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
    }
    /**
     * Creates new form Usuario
     */    /**
     * Creates new form Usuario
     */    /**
     * Creates new form Usuario
     */    /**
     * Creates new form Usuario
     */
    public Usuario() {
        initComponents();
    }
    
    private void actualizarAsientosDisponibles() {
        cmbCombo.removeAllItems();
        for (int i = 1; i <= operacion.getAsientosDisponibles().size(); i++) {
            cmbCombo.addItem("Asiento " + i);
        }
    }
    
    private void venderBoleto() {
        String nombre = txtNombre.getText();
        String destino = txtDestino.getText();
        double precio = Double.parseDouble(txtPrecio.getText());
        int asientoSeleccionado = cmbCombo.getSelectedIndex() + 1;
        
        operacion.venderBoleto(nombre, destino, precio, asientoSeleccionado);
        JOptionPane.showMessageDialog(this, "Boleto vendido con éxito.");
    }
    
       public static void main(String[] args) {
        Operation operacion = new Operation();
        new UsuarioVenderBoleto(operacion).setVisible(true);
    }

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtDestino = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        cmbCombo = new javax.swing.JComboBox<>();
        btnAceptar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Usuario");

        cmbCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre");

        jLabel3.setText("Destino");

        jLabel4.setText("Precio");

        jLabel5.setText("Asiento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPrecio)
                    .addComponent(txtDestino)
                    .addComponent(txtNombre)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(0, 462, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnAceptar)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
       // Obtener valores de los campos
    String nombre = txtNombre.getText();
    String destino = txtDestino.getText();
    double precio = Double.parseDouble(txtPrecio.getText());
    int asientoSeleccionado = cmbCombo.getSelectedIndex() + 1;
    Operation operacion = new Operation();

    // Validar que los campos no estén vacíos
    if (nombre.isEmpty() || destino.isEmpty() || precio == 0) {
        JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        precio = Double.parseDouble(txtPrecio.getText());
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "El precio ingresado no es válido.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Verificar que se haya seleccionado un asiento
    if (asientoSeleccionado == 0) {
        JOptionPane.showMessageDialog(this, "Por favor, seleccione un asiento.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Llamar al método para vender el boleto
    operacion.venderBoleto(nombre, destino, precio, asientoSeleccionado);

    // Mostrar mensaje de éxito
    JOptionPane.showMessageDialog(this, "Boleto vendido con éxito.");

    // Actualizar los asientos disponibles en el formulario de asientos
    FormAsientos.mostrarAsientos();
    }//GEN-LAST:event_btnAceptarActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JComboBox<String> cmbCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
